Repository kubernetes-sigs/contributor-playground, pull requests merged in 2018-08, with the labels that each got.

#1 Added "denver" directory for the upcoming open source orientation at …
  README.md
  denver/OWNERS
  denver/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#11 Add workshop participants to denver OWNERs
  denver/OWNERS
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, sig/contributor-experience, size/XS

#8 Add about me file for carlisia
  denver/carlisia.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10 Evillgenius75 intro file
  denver/evillgenius75.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#13 Issue3: Adding intro file for matthewbrahms
  denver/matthewbrahms.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9 Add introduction file for TheGhostHuCodes
  denver/TheGhostHuCodes.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
