Repository kubernetes-sigs/contributor-playground, pull requests merged in 2018-12, with the labels that each got.

#105 add a new repo for a talk at the Paris Open Source Summit
  paris/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#107 Add instructions for the Issues and PR exercises. These both doc how…
  exercises/issues.md
  exercises/prs.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, sig/contributor-experience, size/M

#108 Adds README describing the purpose of the exercises/ folder
  exercises/README.md
  exercises/issues.md
Labels: approved, cncf-cla: yes, lgtm, sig/contributor-experience, size/S

#111 add a title to the README
  paris/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#116 Adding OWNERS for workshop
  seattle/OWNERS
Labels: approved, cncf-cla: yes, lgtm, sig/contributor-experience, size/M

#159 Add idealhack as an approver at NCW Seattle
  seattle/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#163 Correcting typo in README.md
  seattle/README.md
Labels: approved, cncf-cla: yes, kind/bug, lgtm, sig/contributor-experience, size/XS

#168 Table 1 PR exercise
  seattle/table1.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#185 Test - dummy pr
  seattle/contributor-pauline
Labels: approved, cncf-cla: yes, lgtm, size/XS

#177 add prerequisites files
  seattle/workshop-prerequisites.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#167 Renaming Kubernetes in K8s in README.md
  seattle/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#173 new file: intro table 3
  seattle/intro.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS

#176 Bad file
  seattle/table9.exe
Labels: approved, cncf-cla: yes, lgtm, size/XS

#181 Added nice cat, closes #166
  seattle/cat.jpg
Labels: approved, cncf-cla: yes, lgtm, size/XS

#183 This repo needs more cowbell
  seattle/MoreCowbell.txt
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS, ¯\_(ツ)_/¯

#184 hello
  seattle/hi.me
Labels: approved, cncf-cla: yes, lgtm, sig/contributor-experience, size/XS

#171 here is an example new file that can be deleted at any time
  seattle/ppl/gitbytes.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS, ¯\_(ツ)_/¯

#175 Added my introduction
  seattle/intro.md
Labels: approved, cncf-cla: yes, lgtm, sig/contributor-experience, size/XS

#180 This project was lacking main func. Adding it here.
  seattle/test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#187 adding new file
  seattle/tokt
Labels: approved, cncf-cla: yes, lgtm, size/XS

#172 added schedule with naptime
  seattle/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#186 PR-practice
  seattle/cchengleo
Labels: approved, cncf-cla: yes, lgtm, size/XS

#165 Add table4 github ids
  seattle/TABLE4
Labels: approved, cncf-cla: yes, lgtm, size/XS

#191 create test
  seattle/test
Labels: approved, cncf-cla: yes, lgtm, sig/contributor-experience, size/XS

#192 Unicorns!
  seattle/unicorns.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, sig/contributor-experience, size/XS

#196 Added new beautiful poeam
  seattle/cat-poems/She-Sights-a-Bird-Emily-Dickinson.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#197 Fix title
  seattle/README.md
Labels: approved, cncf-cla: yes, kind/feature, lgtm, sig/contributor-experience, size/XS

#198 Create table5.yml
  seattle/table5.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#199 FIX: mine intro
  seattle/anton.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#204 Fix typo
  seattle/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
