Repository kubernetes-sigs/contributor-playground, pull requests merged in 2018-11, with the labels that each got.

#17 Add shanghai directory for the new contributors summit
  shanghai/OWNERS
  shanghai/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#18 Hello, Shanghai
  shanghai/hello-shanghai.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#19 Fix the GitHub handle for Puja
  shanghai/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#20 Added Tim as an approver so that we can fix things with the playgroun…
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#56 hello, shanghai!
  shanghai/hello.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#59 Create hellowifi.md
  shanghai/hellowifi.md
Labels: approved, cncf-cla: yes, lgtm, sig/contributor-experience, size/S

#69 Add hello from table X
  shanghai/OWNERS
  shanghai/hello-from-table-x.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, sig/contributor-experience, size/XS

#60 Test
  shanghai/hello-shanghai.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#84 Hello everyone
  shanghai/knock-knock.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#92 Tomeyday's first commit for PR testing in Shanghai
  shanghai/thomas.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#88 Add myself to the owner list
  shanghai/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS, ¯\_(ツ)_/¯

#97 Create qiniu-contrubitors.md
  shanghai/qiniu-contrubitors.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#57 fix quietcoolwu name
  shanghai/OWNERS
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#61 New test PR
  shanghai/OWNERS
  shanghai/hello-kubernetes.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, sig/contributor-experience, size/XS

#82 welcome to hangzhou
  shanghai/welcome-to-hangzhou.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#67 Add a file
  shanghai/k8s_is_great.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#78 PR test
  shanghai/k8s_is_great.md
Labels: approved, lgtm, size/XS

#99 Addd shanghai/qiniu subdirectory.
  shanghai/qiniu/OWNERS
  shanghai/qiniu/README.md
  shanghai/qiniu/contrubitors.md
Labels: approved, cncf-cla: yes, lgtm, sig/contributor-experience, size/XS

#101 Add hello in shanghai/qiniu
  shanghai/qiniu/hello.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#104 test
  shanghai/qiniu/hello2.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
