Repository kubernetes-sigs/contributor-playground, pull requests merged in 2019-07, with the labels that each got.

#352 Remove redundant OWNERS_ALIASES file
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/S

#353 Add a directory for OSCON 2019 workshop
  oscon-2019/OWNERS
  oscon-2019/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#351 Add nikhita as approver
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#354 Add cndt-2019/OWNERS for training in JP
  cndt-2019/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/S

#355 Add sollys real email
  oscon-2019/sollys-real-actual-email.txt
Labels: approved, cncf-cla: yes, kind/cleanup, kind/feature, lgtm, size/XS

#356 Add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, sig/contributor-experience, size/M

#357 Add oomichi.md as a test
  cndt-2019/oomichi.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#358 Remove oomichi.md for a permission test
  cndt-2019/oomichi.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#359 Add README.md to cndt-2019
  cndt-2019/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#365 add yuichi10.md file for cndt 2019
  cndt-2019/yuichi10.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#362 My test pull request
  cndt-2019/mumoshu.test.txt
Labels: approved, cncf-cla: yes, kind/feature, kind/flake, lgtm, size/XS

#366 Add gopher.md to cndt-2019.
  cndt-2019/gopher.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#367 add mzd.md to cndt-2019
  cndt-2019/mzd.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#371 Jiye/20190722 nb
  cndt-2019/hello-jiye.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#370 Hands-on
  cndt-2019/matsuda.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#368 add kmatsumoto.md
  cndt-2019/kmatsumoto.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#369 Add file for practice
  cndt-2019/sagara177.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#374 hello k8s contributor's world
  cndt-2019/my_awesome_doc.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, sig/testing, size/XS

#363 Add group photo
  cndt-2019/README.md
  cndt-2019/group-photo.jpg
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#375 Add file sumida.md
  cndt-2019/sumdia.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#378 Finish my upstream training
  cndt-2019/mumoshu.test.txt
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS
