Repository kubernetes-sigs/contributor-playground, pull requests merged in 2019-12, with the labels that each got.

#429 Add foo.md
  ood-2019/workdir/foo.md
Labels: approved, cncf-cla: yes, kind/bug, lgtm, sig/testing, size/XS

#430 Add masaru-oki.md
  ood-2019/workdir/masaru-oki.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#431 Add khrd.md
  ood-2019/workdir/khrd.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#432 add ShotaMuto.md
  ood-2019/workdir/ShotaMuto.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#437 Add hands_on.md
  ood-2019/hands_on.md
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#433 Add y_nishimura.md
  ood-2019/workdir/y_nishimura.md
Labels: approved, cncf-cla: yes, kind/bug, lgtm, sig/testing, size/XS, ¯\_(ツ)_/¯

#444 Add group photo
  ood-2019/README.md
  ood-2019/images/ood2019-photo.jpg
Labels: approved, cncf-cla: yes, lgtm, size/XS

#445 add keruru.md
  ood-2019/workdir/keruru.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#447 Add my note to ood-2019
  ood-2019/workdir/atoato88.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS, ¯\_(ツ)_/¯

#438 Update OOD2019 upstream training prerequisites instruction
  ood-2019/docs/attendee-prerequisites.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M
