Repository kubernetes-sigs/contributor-playground, pull requests merged in 2019-11, with the labels that each got.

#387 Add initial contents for OOD 2019
  ood-2019/README.md
  ood-2019/docs/attendee-prerequisites.md
  ood-2019/workdir/shu-mutou.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#388 Update attendee-prerequisites.md on ood-2019
  ood-2019/docs/attendee-prerequisites.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#389 Add San Diego Workshop folder
  sandiego/OWNERS
  sandiego/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#390 Update San Diego OWNERS with random intro contributors.
  sandiego/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/M

#395 Add Room 15's change
  sandiego/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#397 Add "have fun"
  sandiego/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#400 adding name to the readme
  sandiego/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#422 Add task to register to slack in prerequisite in ood-2019
  ood-2019/docs/attendee-prerequisites.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#424 Add an OOD 2019 logo picture to README.md
  ood-2019/README.md
  ood-2019/docs/attendee-prerequisites.md
  ood-2019/images/ood2019-logo.png
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#425 Add description for slack channel
  ood-2019/docs/attendee-prerequisites.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
