Repository kubernetes-sigs/contributor-playground, pull requests merged in 2019-06, with the labels that each got.

#272 Hello from Diversity lunch of Kube con
  barcelona/testPR.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#243 added eveything-is-awesome.txt
  barcelona/eveything-is-awesome.txt
Labels: approved, cncf-cla: yes, lgtm, lifecycle/rotten, size/XS

#253 Add doc link to the Barcelona K8s contrib doc
  barcelona/README.md
Labels: approved, cncf-cla: yes, lgtm, lifecycle/rotten, size/XS

#262 Add hello-world comment into README.
  barcelona/README.md
Labels: approved, cncf-cla: yes, lgtm, lifecycle/rotten, size/XS

#267 Adding the date of the workshop to the README
  barcelona/README.md
Labels: approved, cncf-cla: yes, lgtm, lifecycle/rotten, size/XS

#271 Add a logo
  barcelona/logo.jpg
Labels: approved, cncf-cla: yes, lgtm, lifecycle/rotten, size/XS

#291 my pretty PR
  barcelona/prettyPR.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#110 Add corresponding change in prs.md
  exercises/prs.md
Labels: approved, cncf-cla: yes, lgtm, lifecycle/rotten, sig/contributor-experience, size/XS

#214 My First PR.
  seattle/test.md
Labels: approved, cncf-cla: yes, kind/bug, lgtm, lifecycle/rotten, sig/contributor-experience, size/XS

#295 my first pull request
  barcelona/myfile.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#296 Shanghai 2019 prep
  shanghai/2018/OWNERS
  shanghai/2018/README.md
  shanghai/2018/faq.md
  shanghai/2018/hello-from-table-x.md
  shanghai/2018/hello-kubernetes.md
  shanghai/2018/hello-shanghai.md
  shanghai/2018/hello.md
  shanghai/2018/hellowifi.md
  shanghai/2018/joke.md
  shanghai/2018/k8s_is_great.md
  shanghai/2018/knock-knock.md
  shanghai/2018/thomas.md
  shanghai/2018/welcome-to-hangzhou.md
  shanghai/2019/OWNERS
  shanghai/2019/README.md
  shanghai/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/L

#297 testing CLA with new lines
  shanghai/2019/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#316 Add myself to Shanghai approvers list
  shanghai/2019/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#317 my test pr
  shanghai/2019/prtrial.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, sig/testing, size/XS

#338 add makefile
  shanghai/2019/makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#331 fix year in README
  shanghai/2019/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#334 Add nginx Dockerfile
  shanghai/2019/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/M

#319 update pr-test.md for pull request test
  shanghai/2019/pr-test.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#320 Create hello.md
  shanghai/2019/hello.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#326 test pr
  shanghai/2019/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#328 Add ashahab to OWNERS
  shanghai/2019/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#329 testing github
  shanghai/2019/testing
Labels: approved, cncf-cla: yes, lgtm, size/XS

#332 Add pluradj to Shanghai 2019 approvers
  shanghai/2019/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#337 Update README.md
  shanghai/2019/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#340 this is a new feature
  shanghai/2019/new_feature.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#342 Introduce myself
  shanghai/2019/TaylorHere.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#344 new pull request in shanghai
  shanghai/2019/new_pullrequest
Labels: approved, cncf-cla: yes, lgtm, size/XS

#345 my test pull request
  shanghai/2019/test.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS

#349 add a hello words for test PR
  shanghai/2019/new_feature.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
