Repository kubernetes-sigs/contributor-playground, pull requests merged in 2019-05, with the labels that each got.

#235 Add Barcelona workshop folder
  barcelona/OWNERS
  barcelona/README.md
Labels: approved, cncf-cla: yes, lgtm, sig/contributor-experience, size/S

#234 Updated OWNERS files to use go.k8s.io for pointing to docs
  OWNERS
  OWNERS_ALIASES
  bay-area-kube-day/OWNERS
  beijing/OWNERS
  denver/OWNERS
  paris/OWNERS
  seattle/OWNERS
  shanghai/OWNERS
  shanghai/qiniu/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/S

#238 Showing bot automation
  barcelona/201.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#246 add Lubomir to Barcelona OWNERS file
  barcelona/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#257 Update the location of the New Contributor Summit
  barcelona/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#245 add myfile.md
  barcelona/myfile.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#247 added foo
  barcelona/foo.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#244 Greetings from Sweden
  barcelona/hejhej.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#268 Missing comma at 201.md file
  barcelona/201.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#265 testing the k8s github flow
  barcelona/toto.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#273 Yes I'm so proud ! Thank You Hippie
  barcelona/gaelle.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
