Repository kubernetes-sigs/contributor-playground, pull requests merged in 2020-05, with the labels that each got.

#465 Add work folder for training on Kubernetes Fest Tokyo 2020
  kft-2020/OWNERS
  kft-2020/README.md
  kft-2020/docs/attendee-prerequisites.md
  kft-2020/hands_on.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/L, tide/merge-method-squash

#466 Add link to code of conduct
  kft-2020/docs/attendee-prerequisites.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#467 Add logo and event url to README
  kft-2020/README.md
  kft-2020/images/kubernetes-tokyo-transparent.png
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#468 Update attendee-prerequisites.md for kft-2020
  kft-2020/docs/attendee-prerequisites.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#470 Change event name to KubeFest Tokyo 2020
  kft-2020/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#471 Add jp-mentoring channel of slack to kft-2020/doc/sattendee-prerequisites.md
  kft-2020/docs/attendee-prerequisites.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS
