Repository kubernetes-sigs/contributor-playground, pull requests merged in 2020-09, with the labels that each got.

#532 Update attendee-prerequisites in cndt2020
  cndt-2020/docs/attendee-prerequisites.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#536 Add foo.md for demo.
  cndt-2020/workdir/foo.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, sig/testing, size/XS

#537 Add inami.md for demo
  cndt-2020/workdir/inami.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#542 [Fix/Docs] Add bo0km4n markdown for demo
  cndt-2020/workdir/bo0km4n.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#543 Add naotospace.md for exercise
  cndt-2020/workdir/naotospace.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#538 Add daniel.md for demo
  cndt-2020/workdir/daniel.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, sig/testing, size/XS

#546 Add yamagai.md for demo.
  cndt-2020/workdir/yamagai.md
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/XS

#547 Add yuhara.md
  cndt-2020/workdir/yuhara.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#548 Add akitok.md for demo
  cndt-2020/workdir/akitok.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#545 Add kennygt51.md for kubernetes upstream training.
  cndt-2020/workdir/kennygt51.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, sig/testing, size/XS

#539 :memo: Add sample file for demo
  cndt-2020/workdir/tetsuya28.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#540 Add renjikari md
  cndt-2020/workdir/renjikari.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, sig/testing, size/XS

#541 Add tsubasaxzzz.md
  cndt-2020/workdir/tsubasaxzzz.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, sig/testing, size/XS

#549 add practice demo file
  cndt-2020/workdir/rueyjye.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#551 add shimada.md
  cndt-2020/workdir/shimada.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#553 add shuzokato.md
  cndt-2020/workdir/shuzokato.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#554 Add mfykmn.md
  cndt-2020/workdir/mfykmn.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#555 Add ymurase.md
  cndt-2020/workdir/ymurase.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, sig/testing, size/XS, ¯\_(ツ)_/¯

#556 Add hana_enjoy.md
  cndt-2020/workdir/hana_enjoy.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, sig/testing, size/XS

#557 Add masakihara.md for training.
  cndt-2020/workdir/masakihara.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#558 Add yassan.md for Kubernetes upstream training in CNDT2020
  cndt-2020/workdir/yassan.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#559 Add tn.md
  cndt-2020/workdir/tn.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, sig/testing, size/XS

#561 add mochizuki875.md
  cndt-2020/workdir/mochizuki875.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#562 Add micheam.md
  cndt-2020/workdir/micheam.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#563 [add] hogehoge.md
  cndt-2020/workdir/hogehoge.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, sig/testing, size/XS, ¯\_(ツ)_/¯

#564 add katsuhisakitano.md for kubernetes upstream training
  cndt-2020/workdir/katsuhisakitano.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#565 Add hikimochi.md
  cndt-2020/workdir/hikimochi.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#566 nao-ri_commnet.md for demo
  cndt-2020/workdir/nao-ri_commnet.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#567 Add attendees photo to README
  cndt-2020/README.md
  cndt-2020/images/cndt-2020-01.png
  cndt-2020/images/cndt-2020-02.png
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#569 Add sakaia2.md
  cndt-2020/workdir/sakaia2.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#568 Add sakaia.md
  cndt-2020/workdir/sakaia.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#570 This my greeting contribution
  cndt-2020/workdir/amomsi.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
