Repository kubernetes-sigs/contributor-playground, pull requests merged in 2020-06, with the labels that each got.

#473 Create workdir and update hands_on.md for kft-2020
  kft-2020/hands_on.md
  kft-2020/workdir/toyoda.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#472 Add event shedule url to README.md
  kft-2020/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#474 Add checking company policy before joining workshop
  kft-2020/docs/attendee-prerequisites.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#475 Add request for using thread in Slack if question
  kft-2020/docs/attendee-prerequisites.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#478 Add foo.md for kft-2020 workshop
  kft-2020/workdir/foo.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, sig/testing, size/XS

#479 Add kiyoshim55.md for kft-2020 workshop
  kft-2020/workdir/kiyoshim55.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, sig/testing, size/XS

#480 Add hichihra.md for kft-2020 workshop
  kft-2020/workdir/hichihara.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#482 Add kashinoki38.md for kft-2020 workshop
  kft-2020/workdir/kashinoki38.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#481 Add gky360.md for kft-2020 workshop
  kft-2020/workdir/gky360.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#483 Add eba.md for kft-2020 workshop
  kft-2020/workdir/eba.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#485 Add bells17.md for kft-2020
  kft-2020/workdir/bells17.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, sig/testing, size/XS

#484 Add foo.md for kft-2020
  kft-2020/workdir/MeYururi.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, sig/testing, size/XS

#486 Add degiple.md for kft-2020 workshop by degiple
  kft-2020/workdir/degiple.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, sig/testing, size/XS

#487 add workshop impression
  kft-2020/workdir/kimullaa.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#488 Add yktsubo.md for kft2020 workshop.
  kft-2020/workdir/yktsubo.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#489 Add hyab.md for kft-2020 workshop
  kft-2020/workdir/hyab.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, sig/testing, size/XS

#491 add rkgy.md for kft-2020 workshop
  kft-2020/workdir/rkgy.md
Labels: approved, cncf-cla: yes, lgtm, sig/testing, size/XS

#494 Add tkms0106.md
  kft-2020/workdir/tkms0106.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#495 Add nnasaki.md
  kft-2020/workdir/nnasaki.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#497 Add translucens.md
  kft-2020/workdir/translucens.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#490 Add transnano.md for kft-2020
  kft-2020/workdir/transnano.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#498 Add thanks.md for kft-2020 workshop
  kft-2020/workdir/thanks.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#493 Add waiwai.md for kft-2020 workshop
  kft-2020/workdir/waiwai.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#500 add faruryo.md for kft-2020 workshop
  kft-2020/workdir/faruryo.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#501 Add rkasa.md for kft-2020 workshop
  kft-2020/workdir/rkasa.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#502 Add add_ushi_foo_md
  kft-2020/workdir/add_ushi_foo_md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#505 Add nishipy.md
  kft-2020/workdir/nishipy.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#496 Add mizumoto.md for kft-2020
  kft-2020/workdir/mizumoto.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#504 Add eto.md
  kft-2020/workdir/eto.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#509 Add minamiii.md
  kft-2020/workdir/minamiii_md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#512 Add attendee images
  kft-2020/README.md
  kft-2020/images/kft2020-01.png
  kft-2020/images/kft2020-02.png
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#350 Add remote directory
  remote/LEARNERS
  remote/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#519 Update OWNERS to reflect current contribex leads
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS
