Repository kubernetes-sigs/contributor-playground, pull requests merged in 2021-06, with the labels that each got.

#688 Add p0r7m.md
  india/k8s-blr-2021/workdir/p0r7m.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#686 kiran.md
  india/k8s-blr-2021/workdir/kiran.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#687 Add prasad.md
  india/k8s-blr-2021/workdir/prasad.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#691 Add palnabarun to remote/LEARNERS
  remote/LEARNERS
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#695 india: initialize workspace for workshop at KCD BLR
  india/kcd-blr-2021/OWNERS
  india/kcd-blr-2021/README.md
  india/kcd-blr-2021/attendee-instructions.md
  india/kcd-blr-2021/workdir/palnabarun.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/L

#696 add description for Madhav Jivrajani in facilitators for kcd-blr-2021
  india/kcd-blr-2021/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#697 adding arsh in kcd 2021 facilitators
  india/kcd-blr-2021/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#698 kcdblr: Update palnabarun workdir
  india/kcd-blr-2021/workdir/palnabarun.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#700 Create rahul.md
  india/kcd-blr-2021/workdir/rahul.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#705 update vikramcse workdir
  india/kcd-blr-2021/workdir/vikramcse.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#703 update nitesh seram workdir
  india/k8s-blr-2021/workdir/Awesome session
  india/kcd-blr-2021/workdir/niteshseram.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#706 india: avinash init
  india/kcd-blr-2021/workdir/avinash.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#708 Create ans-max
  india/kcd-blr-2021/workdir/ans-max
Labels: approved, cncf-cla: yes, lgtm, size/XS

#709 Create hello-ram.md
  india/kcd-blr-2021/workdir/hello-ram.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#699 kcdblr: Update pavanraga workdir
  india/kcd-blr-2021/workdir/pavanraga.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#710 Create priyamsamanta
  india/kcd-blr-2021/workdir/priyamsamanta
Labels: approved, cncf-cla: yes, lgtm, size/XS

#712 kcdblr: Add rahulgrover99 workdir
  india/kcd-blr-2021/workdir/rahulgrover99.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#713 Create gkadam
  india/kcd-blr-2021/workdir/gkadam
Labels: approved, cncf-cla: yes, lgtm, size/XS

#714 Add india/workdir/vijaygenius123
  india/k8s-blr-2021/workdir/vijaygenius123.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#716 Just one commit
  india/kcd-blr-2021/workdir/rohanpurekar.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#718 PR
  india/kcd-blr-2021/workdir/nilimachavan.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#719 added file.
  india/kcd-blr-2021/workdir/sneha_k.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#720 kcdblr: Add akshay.md file to kcd-blr-2021 workdir
  india/kcd-blr-2021/workdir/akshay.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#722 kcdblr : added my .md file
  india/kcd-blr-2021/workdir/sachin.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#723 Vibhor Rawat addition
  india/kcd-blr-2021/workdir/vibhorr.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#717 add ishitakeshawani.md file
  india/kcd-blr-2021/workdir/ishitakeshawani.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, tide/merge-method-squash

#724 Just a simple file commit
  india/kcd-blr-2021/workdir/h2g2.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#726 Commiting ..
  india/kcd-blr-2021/workdir/Sachin.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#730 Added my workdir
  india/kcd-blr-2021/workdir/VedantKakde.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#732 First commit to update dbhaskaran workspace
  india/kcd-blr-2021/workdir/dbhaskaran.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#736 Adding new markdown file
  india/kcd-blr-2021/workdir/VikasManohar.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#737 added workdir file sameer.md
  india/kcd-blr-2021/workdir/sameer.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#740 Kcdblr/vijaygenius123
  india/kcd-blr-2021/workdir/vijaygenius123.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, tide/merge-method-squash

#746 Adding the new file sunish.md
  india/kcd-blr-2021/sunish.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#747 first commit ragsarang
  india/kcd-blr-2021/workdir/ragsarang.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#750 Create abhishek-kumar.md
  india/kcd-blr-2021/workdir/abhishek-kumar.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#752 PR-KCDBLR'21
  india/kcd-blr-2021/workdir/yusuf.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#753 Documentation
  india/kcd-blr-2021/workdir/shankarganesh.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#748 Testing PR
  india/kcd-blr-2021/workdir/vaibhavp.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#755 kcdblr: add event photos
  india/kcd-blr-2021/README.md
  india/kcd-blr-2021/assets/img1.jpg
  india/kcd-blr-2021/assets/img2.jpg
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#754 kcdblr: Add Prathamesh Shanbhag
  india/kcd-blr-2021/workdir/prathameshsshanbhag.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#751 Add benson.md
  india/kcd-blr-2021/workdir/benson.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#756 first PR to K8s
  india/kcd-blr-2021/workdir/praveen.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, tide/merge-method-squash
