Repository kubernetes-sigs/contributor-playground, pull requests merged in 2021-02, with the labels that each got.

#585 Create adhoc/workdir for practicing anytime
  japan/adhoc/workdir/.gitkeep
Labels: approved, cncf-cla: yes, lgtm, size/XS

#586 india: init k8s bangalore contributor workshop
  india/OWNERS
  india/README.md
  india/k8s-blr-2021/OWNERS
  india/k8s-blr-2021/README.md
  india/k8s-blr-2021/attendee-instructions.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#587 india/k8s-blr-2021: add workdir dir and example file
  india/k8s-blr-2021/README.md
  india/k8s-blr-2021/workdir/example.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#588 k8s-blr-2021: update slides URL
  india/k8s-blr-2021/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#590 Add nikhita.md
  india/k8s-blr-2021/workdir/nikhita.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#589 Add woof.md (k8s blr workshop )
  india/k8s-blr-2021/workdir/woof.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#591 added new user
  india/k8s-blr-2021/workdir/dinesh_kumar.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#592 Added rtnpro.md.
  india/k8s-blr-2021/workdir/rtnpro.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#595 Added something new
  india/k8s-blr-2021/workdir/cool_new_feature.md
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#600 RBT Feedback. Adding rbt.md
  india/k8s-blr-2021/workdir/rbt.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#594 Add feedback in a file
  india/k8s-blr-2021/workdir/mahendra.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#597 Add hussaina.md
  india/k8s-blr-2021/workdir/hussaina.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#593 first pr
  india/k8s-blr-2021/workdir/adizz.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#596 Declaring that K8s is awesome
  india/k8s-blr-2021/workdir/K8sIsAwesome.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#598 Add prabhu.md
  india/k8s-blr-2021/workdir/prabhu.md
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#599 Ayush_Das
  india/k8s-blr-2021/workdir/Ayush_Das.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#602 First of many times
  india/k8s-blr-2021/workdir/srinivasakartheek.md
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#603 Added feedback from arjun921
  india/k8s-blr-2021/workdir/feedback_arjun.md
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#604 Add rajeev.md
  india/k8s-blr-2021/workdir/rajeev.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#605 Add sample markdown file
  india/k8s-blr-2021/workdir/anubhav.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#607 add daemon1024.md
  india/k8s-blr-2021/workdir/daemon1024.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#608 First commit while attending "Contributing to Kubernetes 101" workshop.
  india/k8s-blr-2021/workdir/ashwani.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#609 Review Added !!
  india/k8s-blr-2021/workdir/grpit.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#610 initial commit
  india/k8s-blr-2021/workdir/mehul.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#611 Add sourabhdeshmukh.md
  india/k8s-blr-2021/workdir/sourabhdeshmukh.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#612 Create longwuyuan.md
  india/k8s-blr-2021/workdir/longwuyuan.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#613 Added feedback from Varen
  india/k8s-blr-2021/workdir/varen.md
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#615 Hello, Kubernetes!
  india/k8s-blr-2021/workdir/akash.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#617 add doc on why fixing bugs is a good start
  india/k8s-blr-2021/workdir/why-fixing-bugs-is-a-good-start.md
Labels: approved, cncf-cla: yes, kind/documentation, kind/feature, lgtm, size/S

#618 Hola, K8s!
  india/k8s-blr-2021/workdir/yudocaa.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#614 anjul.md
  india/k8s-blr-2021/anjul.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#619 Add recursion.md
  india/k8s-blr-2021/workdir/recursion.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#621 fisrt commit
  india/k8s-blr-2021/workdir/yashraj.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#622 Great session.
  india/k8s-blr-2021/workdir/Awesome session.
Labels: approved, cncf-cla: yes, lgtm, size/XS

#627 fixed location
  india/k8s-blr-2021/workdir/anjul.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#625 Create srikrishnabh.md
  india/k8s-blr-2021/workdir/srikrishnabh.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#583 test
  shanghai/2020/hello-wikix.md
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#628 k8s-blr-2021: add group photo
  india/k8s-blr-2021/README.md
  india/k8s-blr-2021/assets/1.jpg
  india/k8s-blr-2021/assets/2.jpg
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#606 thanks
  india/k8s-blr-2021/workdir/siddharth.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#584 Test PR.
  japan/adhoc/workdir/s-kawamura-w664.md
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS
