Repository kubernetes-sigs/contributor-playground, pull requests merged in 2021-12, with the labels that each got.

#914 Update oomichi's bio to approver on kubespray
  japan/ossj-2021/README.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#916 add s-kawamura-w664.md for demo
  japan/ossj-2021/workdir/s-kawamura-w664.md
Labels: kind/documentation, lgtm, sig/node, size/XS, approved, cncf-cla: yes

#917 add yasuraok.md
  japan/ossj-2021/workdir/yasuraok.md
Labels: kind/documentation, lgtm, sig/node, size/XS, approved, cncf-cla: yes

#918 add shnmorimoto.md for ossj 2021 upstream training
  japan/ossj-2021/workdir/shnmorimoto.md
Labels: kind/documentation, lgtm, sig/node, size/XS, approved, cncf-cla: yes, ¯\_(ツ)_/¯

#922 Add photo for ossj-2021
  japan/ossj-2021/README.md
  japan/ossj-2021/images/ossj-2021-01.png
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#924 Add foo md kuji2(retry)
  japan/ossj-2021/workdir/kujiraitakahiro-w664.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes
