Repository kubernetes-sigs/contributor-playground, pull requests merged in 2021-07, with the labels that each got.

#759 Initial PR
  india/kcd-blr-2021/workdir/chetan.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#757 Created karl_dasan.md
  india/kcd-blr-2021/workdir/karl_dasan.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#761 First Commit
  remote/LEARNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS, ¯\_(ツ)_/¯

#762 remote: add ghc-osd-2021 dir
  remote/ghc-osd-2021/OWNERS
  remote/ghc-osd-2021/README.md
  remote/ghc-osd-2021/attendee-instructions.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#763 bootstrap an india/remote directory for people coming in from recordings
  india/remote/OWNERS
  india/remote/README.md
  india/remote/learners/sample.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#766 Create nikhita.md
  remote/ghc-osd-2021/nikhita.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#767 Test commit from OSD 2021
  remote/ghc-osd-2021/hanna-test.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#768 test commit OSD
  remote/ghc-osd-2021/lakshya.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#769 add palnabarun as a remote learner in India
  india/remote/learners/palnabarun.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#764 adding arsh to india/remote approvers
  india/remote/OWNERS
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#765 Add self to india/remote OWNERS
  india/remote/OWNERS
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#770 Add knidhikaranth as a remote learner in India
  india/remote/learners/kkaranth.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#771 Added Soumik to learners list.
  india/remote/learners/soumik.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#773 Add aveshag as a new learner in India
  india/remote/learners/KUBDOC.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#772 Added my first commit for practice and also removed someone's case-insentive commit
  india/kcd-blr-2021/workdir/slayer321.md
  india/remote/learners/numan.md
Labels: approved, cncf-cla: yes, kind/cleanup, kind/documentation, lgtm, size/XS

#774 Ritika added to learners.
  india/remote/learners/ritika.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#777 commit message from live demo
  india/remote/learners/arsh_demo.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#778 first pr
  india/remote/learners/santosh_kumar_patro.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#779 Add Pritish As A Contributor
  india/remote/learners/pritish.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#781 Add divya as contributor
  india/remote/learners/divyasri.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#780 First PR to kubernetes
  india/remote/learners/SnehaMallik.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#782 first pr will go now
  india/remote/learners/index.ts.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#785 Demo
  india/remote/learners/udit.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#789 Add Rupesh as contributor
  india/remote/learners/Rupesh.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#783 saikiran's 1st PR to kubernetes repo
  india/kcd-blr-2021/workdir/sachin.md
  india/remote/learners/sjagini.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#784 Hello!
  india/remote/learners/monali.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#788 1st demo pull request
  india/remote/learners/Kamaljeet_demo.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#791 Heya
  india/remote/learners/sp7infinity.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#792 first commit
  india/remote/learners/aabhas.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#794 Create purneswar.md
  india/remote/learners/purneswar.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#790 starting with opensource.
  india/remote/learners/komal.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#808 add bhanu as a remote learner in India
  india/remote/learners/bhanu.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#811 learning open-source
  india/remote/learners/kmahimarun.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#802 Added Paarth as a remote learner in India
  india/remote/learners/paarth.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#776 "Adding myself as a remote learner"
  india/remote/learners/sonu.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#795 Add Varun R as a remote learner in India
  india/remote/learners/varunr.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#796 test pr
  india/remote/learners/omisa.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#797 bkhatri_first_contribution
  india/remote/learners/bkhatri.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#798 Added naishadhv.md for learning purposes
  india/remote/learners/naishadhv.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#799 Add Yavar as a remote learner please
  india/remote/learners/yavar.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#800 first_commit
  india/remote/learners/shreyansh2809.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#801 First Commit
  india/remote/learners/Janukriti.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#803 adding sonipa as remote learner in India
  india/remote/learners/sonipa.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#805 add msikka as a remote learner
  india/remote/learners/msikka.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#806 Added Anujeet Chatterjee as Contributor.
  india/remote/learners/anujeetc.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#807 add aysinha as a remote learner in india for the first open source contribution
  india/remote/learners/aysinha.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#809 adding new
  india/remote/learners/mbansal.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#810 first commit
  india/remote/learners/prateek.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#812 Add harsh as learner in India
  india/remote/learners/harsh.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#813 My first k8s contribution!
  india/remote/learners/cayush.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#824 Adding myself to remote contributors
  india/remote/learners/deut-erium.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#819 Add Aniket as contributor
  india/remote/learners/aniket.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#816 Added george as learner for k8s
  india/remote/learners/georgephilip.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#818 Added Siva as a learner
  india/remote/learners/ssivaprathee.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#821 Added file shriamrut.md to india remote learners
  india/remote/learners/shriamrut.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#822 first commit
  india/remote/learners/yashvardhan.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#823 Kaushik Markdown Created
  india/remote/learners/kganorkar.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#825 add govilakshat1998 as a remote learner in India
  india/remote/learners/govila.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#826 This is Brindon's first Kubernetes Contribution
  india/remote/learners/brindon.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#828 add tanmaym as a remote learner in India
  india/remote/learners/tanmaym.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#829 Add rkailashramesh as a remote learner in India
  india/remote/learners/rkailashramesh.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#830 First commit to K8s Playground
  india/remote/learners/vasundharas.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#831 My first K8S contribution
  india/remote/learners/AbhyudayDixit.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#833 Add thakurso as a remote learner
  india/remote/learners/thakurso.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#815 opensource k8s
  india/remote/learners/giridharaguptha.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#817 Kselvamani k8s
  india/remote/learners/kselvamani.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#834 Add prmehta as a remote learner in India
  india/remote/learners/prmehta.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#835 add karan07krs as a remote learner in India
  india/remote/learners/karank8.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#836 add pratibha as a remote learner
  india/remote/learners/pratibha.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#839 add maheshwariak as a remote learner in India
  india/remote/learners/maheshwariak.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#841 add metalcyanide to learners in india
  india/remote/learners/metalcyanide.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#843 add Daksh as a remote learner in India
  india/remote/learners/dakshberry121.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#840 sgourav first commit to kubernetes project
  india/remote/learners/sgourav.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#849 brazil: add initial directory to hold the NCWs in Brazil
  brazil/OWNERS
  brazil/README.md
  brazil/attendee-instructions.md
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#853 Add ashubhanshi as a remote learner in india
  india/remote/learners/ashubhanshi.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#851 add Aakanksha as a remote learner in India
  india/remote/learners/goyalaa.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#850 Add Krithika as a remote learner
  india/remote/learners/ksuwarna.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#844 Add Chopraan as remote learner in India
  india/remote/learners/chopraan.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#854 Add satyamkr as a remote learner in INDIA
  india/remote/learners/satyamkr.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
