Repository kubernetes-sigs/contributor-playground, pull requests merged in 2021-03, with the labels that each got.

#636 Update prerequisite on japan folder
  japan/assets/attendee-prerequisites.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#637 Extract facilitators from slide to README on Japan
  japan/cndo-2021/README.md
  japan/cndt-2019/README.md
  japan/cndt-2020/README.md
  japan/kft-2020/README.md
  japan/ood-2019/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#638 Update hands_on.md of japan
  japan/assets/hands_on.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#639 Add slack name to README in cndo-2021
  japan/cndo-2021/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#640 Move holding date to timetable in cndo-2021
  japan/cndo-2021/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#643 Add foo.md for cndo-2021 demo
  japan/cndo-2021/workdir/foo.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, sig/testing, size/XS

#644 Add foo_hid27k.md for cndo-2021 demo
  japan/cndo-2021/workdir/foo_hide27k.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, sig/testing, size/XS

#645 Add shimodatkh.md
  japan/cndo-2021/workdir/shimodatkh.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#652 Add hourglasshoro.md in cndo-2021
  japan/cndo-2021/workdir/hourglasshoro.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#655 Add japan/cndo-2021/ryusa.md for demo
  japan/cndo-2021/workdir/ryusa.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS, ¯\_(ツ)_/¯

#648 add kzk_test.md for demo
  japan/cndo-2021/workdir/add_kzk_test.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS, ¯\_(ツ)_/¯

#646 Add fiz2buz.md for cndo-2021 demo
  japan/cndo-2021/workdir/fiz2buz.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#647 Add japan/cndo-2021/itkq.md
  japan/cndo-2021/itkq.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, sig/testing, size/XS

#653 Add chez-shanpu.md for cndo2021
  japan/cndo-2021/workdir/chez-shanpu.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS, ¯\_(ツ)_/¯

#658 add udomomo_sample.md
  japan/cndo-2021/workdir/udomomo_sample.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#659 Add ffjlabo.md for cndo-2021 demo
  japan/cndo-2021/workdir/ffjlabo.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#660 Add eiiches.md for CNDO-2021 training
  japan/cndo-2021/workdir/eiiches.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, sig/testing, size/XS

#664 Add ina.md
  japan/cndo-2021/workdir/ina.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#665 Add foo_y-taka-23.md for cndo-2021 demo
  japan/cndo-2021/workdir/foo_y-taka-23.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#666 Add hayato1226.md
  japan/cndo-2021/workdir/hayato1226.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#667 Add butter.md to cndo-2021 for demo
  japan/cndo-2021/workdir/butter.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, sig/testing, size/XS

#669 Add nk.md
  japan/cndo-2021/workdir/nk.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#671 Add shien3.md for cndo-2021.
  japan/cndo-2021/workdir/shien3.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#672 Add foo_naito.md
  japan/cndo-2021/workdir/foo_naito.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#676 Add photo CNDO 2021
  japan/README.md
  japan/cndo-2021/README.md
  japan/cndo-2021/images/cndo-2021-01.png
  japan/cndo-2021/images/cndo-2021-02.png
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#678 Add kos31de.md
  japan/adhoc/workdir/kos31de.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#679 Add README.md for `japan/adhoc` folder
  japan/adhoc/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#680 Add link to youtube for self-study into `/japan/adhoc`
  japan/README.md
  japan/adhoc/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#681 Add video index for adhoc training in japan folder
  japan/adhoc/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS
