Repository kubernetes-sigs/contributor-playground, pull requests merged in 2021-09, with the labels that each got.

#861 Create harkirat-singh.md
  india/kcd-blr-2021/workdir/harkirat-singh.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#862 Add z1cheng as a remote learner
  remote/LEARNERS
Labels: lgtm, size/XS, approved, cncf-cla: yes

#869 Seed Contributor Workshop Dir for UUIC Hackillinois
  remote/hackillinois-osf-2021/OWNERS
  remote/hackillinois-osf-2021/README.md
  remote/hackillinois-osf-2021/attendee-instructions.md
  remote/hackillinois-osf-2021/madhav.md
Labels: kind/documentation, lgtm, size/L, approved, cncf-cla: yes

#872 demo commit
  india/remote/learners/Arul.md
Labels: lgtm, size/XS, approved, cncf-cla: yes
