Repository kubernetes-sigs/contributor-playground, pull requests merged in 2021-11, with the labels that each got.

#890 add foo.md for cndt-2021 demo
  japan/cndt-2021/workdir/foo.md
Labels: kind/documentation, lgtm, sig/testing, size/XS, approved, cncf-cla: yes

#891 add toricls.md
  japan/cndt-2021/workdir/toricls.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#893 add kuma.md for cndt2021 demo
  japan/cndt-2021/workdir/kuma.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#892 add riita10069.md into cndt-2021
  japan/cndt-2021/workdir/riita10069.md
Labels: kind/documentation, lgtm, sig/testing, size/XS, approved, cncf-cla: yes

#894 Add manabusakai.md
  japan/cndt-2021/workdir/manabusakai.md
Labels: kind/documentation, lgtm, sig/testing, size/XS, approved, cncf-cla: yes

#895 Add care0717.md
  japan/cndt-2021/workdir/care0717.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#896 Add rung-test.md to cndt-2021 (training)
  japan/cndt-2021/workdir/rung-test.md
Labels: kind/documentation, lgtm, sig/testing, size/XS, approved, cncf-cla: yes

#897 add kenken-ishiken.md
  japan/cndt-2021/workdir/kenken-ishiken.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#898 add initial-nj.md for CNDT2021 demo
  japan/cndt-2021/workdir/initial-nj.md
Labels: lgtm, sig/testing, size/XS, approved, cncf-cla: yes

#899 add hoge_polar3130.md
  japan/cndt-2021/workdir/hoge_polar3130.md
Labels: kind/documentation, lgtm, sig/node, size/XS, approved, cncf-cla: yes

#900 Add foo_regmarmcem.md to cndt2021
  japan/cndt-2021/workdir/foo_regmarmcem.md
Labels: kind/documentation, lgtm, sig/testing, size/XS, approved, cncf-cla: yes

#901 Add k-srkw-hello-k8s-community.md
  japan/cndt-2021/workdir/k-srkw-hello-k8s-community.md
Labels: kind/documentation, lgtm, sig/testing, size/XS, approved, cncf-cla: yes

#902 add mosuke5.md for demo
  japan/cndt-2021/workdir/mosuke5.md
Labels: kind/documentation, lgtm, sig/testing, size/XS, approved, cncf-cla: yes

#903 Add moguraion.md
  japan/cndt-2021/workdir/moguraion.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#904 Add orimanabu.md
  japan/cndt-2021/workdir/orimanabu.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#905 Add dora56.md
  japan/cndo-2021/workdir/dora56.md
Labels: kind/documentation, lgtm, sig/node, size/XS, approved, cncf-cla: yes

#906 Add ziyi.md for cndt-2021 demo
  japan/cndt-2021/workdir/ziyi.md
Labels: lgtm, sig/testing, size/XS, approved, cncf-cla: yes

#907 Add Photo for CNDT2021
  japan/README.md
  japan/cndt-2021/README.md
  japan/cndt-2021/images/cndt-2021-01.png
  japan/cndt-2021/images/cndt-2021-02.png
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#908 Create preview
  japan/cndt-2021/workdir/preview
Labels: lgtm, size/XS, approved, cncf-cla: yes

#879 Seed Contributor Workshop Dir for UUIC Hackillinois
  remote/hackillinois-osf-2021/Abhinav.md
Labels: lgtm, size/XS, approved, cncf-cla: yes, tide/merge-method-squash

#876 Add Prateek details file
  remote/hackillinois-osf-2021/prateek.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#878 added file for Raul Higareda (worskhop attendee)
  remote/hackillinois-osf-2021/raul-higareda.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#880 Create aniket.md
  remote/hackillinois-osf-2021/aniket.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#874 add details about Dipto
  remote/hackillinois-osf-2021/dipto.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#912 Add workdir for Open Source Summit Japan 2021
  japan/README.md
  japan/ossj-2021/OWNERS
  japan/ossj-2021/README.md
  japan/ossj-2021/images/.placeholder
  japan/ossj-2021/images/logo-ossj-2021.png
  japan/ossj-2021/workdir/.placeholder
Labels: kind/documentation, size/M, lgtm, approved, cncf-cla: yes
