Repository kubernetes-sigs/contributor-playground, pull requests merged in 2022-01, with the labels that each got.

#926 my first contrib PR
  brazil/RicardoKatz.md
Labels: lgtm, kind/cleanup, size/XS, approved, cncf-cla: yes

#928 My First Contrib
  brazil/GeorgeTavares.md
Labels: lgtm, kind/cleanup, size/XS, approved, cncf-cla: yes

#927 my first contribution
  brazil/luizBernardo.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes, triage/accepted

#929 My first PR
  brazil/mauricio-maia.md
Labels: lgtm, kind/cleanup, size/XS, approved, cncf-cla: yes

#931 my first commit
  brazil/WendellBorges.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#932 my first PR
  brazil/otaviocals.txt
Labels: lgtm, kind/cleanup, size/XS, approved, cncf-cla: yes

#936 my first pr
  brazil/FranzwagnerTernus.md
Labels: lgtm, kind/cleanup, size/XS, approved, cncf-cla: yes

#937 My First PR!
  brazil/leandroschwab.md
Labels: lgtm, kind/cleanup, size/XS, approved, cncf-cla: yes

#938 Wesley Dutra: My first PR
  brazil/WesleyDutra.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#940 Fixes slack channels for Brazil
  brazil/attendee-instructions.md
Labels: size/S, kind/documentation, lgtm, approved, cncf-cla: yes, ¯\_(ツ)_/¯

#942 Create AnaLuciaDeFaria.md
  brazil/AnaLuciaDeFaria.md
Labels: lgtm, kind/cleanup, size/XS, approved, cncf-cla: yes

#943 Nw FL
  brazil/Lucas Mendes Barboza
Labels: lgtm, size/XS, approved, cncf-cla: yes

#944 add: my first pr
  brazil/samylle-sales.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#945 First PR - Luis Knob
  brazil/luisdknob.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#939 First Commit - Kube (Neto)
  brazil/JoseNeto.md
Labels: lgtm, kind/cleanup, size/XS, approved, cncf-cla: yes
