Repository kubernetes-sigs/contributor-playground, pull requests merged in 2022-11, with the labels that each got.

#992 Fix Japan upstream training typo
  japan/README.md
Labels: kind/documentation, lgtm, kind/cleanup, size/XS, approved, cncf-cla: yes

#997 Add folder for CNDT 2022
  japan/cndt-2022/README.md
  japan/cndt-2022/images/.placeholder
  japan/cndt-2022/images/logo-cndt-2022.png
  japan/cndt-2022/workdir/.placeholder
  japan/cndt-2022/workdir/s-kawamura-w664.md
Labels: kind/documentation, size/M, lgtm, approved, cncf-cla: yes

#1001 Update cndt-2022 profile
  japan/cndt-2022/README.md
Labels: kind/documentation, lgtm, kind/cleanup, size/XS, approved, cncf-cla: yes

#1003 add s-kawamuraw664-2.md for cndt-2022 demo
  japan/cndt-2022/workdir/s-kawamura-w664-2.md
Labels: kind/documentation, lgtm, sig/testing, size/XS, approved, cncf-cla: yes

#1002 [Add] First commit
  japan/cndt-2022/workdir/RenGoto.md
Labels: kind/documentation, lgtm, sig/testing, size/XS, approved, cncf-cla: yes

#1006 Add hiroyaonoe-hello.md for cndt-2022 training
  japan/cndt-2022/workdir/hiroyaonoe-hello.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1004 Add ystkfujii.md
  japan/cndt-2022/workdir/ystkfujii.md
Labels: lgtm, sig/testing, size/XS, approved, cncf-cla: yes, ¯\_(ツ)_/¯

#1005 add m0riiiii.md for cndt-2022 handson
  japan/cndt-2022/workdir/m0riiiii.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1007 Add eppppi.md for cndt-2022 demo
  japan/cndt-2022/workdir/eppppi.md
Labels: kind/documentation, lgtm, sig/testing, size/XS, approved, cncf-cla: yes

#1008 add soichiro-ueda.md for hands-on
  japan/cndt-2022/workdir/soichiro-ueda.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1009 Add yassan.md for cndt2022 Upstream Training
  japan/cndt-2022/workdir/yassan.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1012 Add training file mochizuki875
  japan/cndt-2022/workdir/mochizuki875.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1010 Add foo.md
  japan/cndt-2022/workdir/foo.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1011 Add jnytnai0613-w664.md for cndt2022
  japan/cndt-2022/workdir/jnytnai0613-w664.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1013 Add the photo on cndt-2022
  japan/README.md
  japan/cndt-2022/README.md
  japan/cndt-2022/images/cndt-2022-01.png
Labels: size/S, lgtm, approved, cncf-cla: yes, ok-to-test

#1018 Add the folder for the training at ood-2022
  japan/ood-2022/README.md
  japan/ood-2022/images/.placeholder
  japan/ood-2022/images/logo-ood-2022.webp
  japan/ood-2022/images/title-ood-2022.webp
  japan/ood-2022/workdir/.placeholder
Labels: kind/documentation, size/M, lgtm, approved, cncf-cla: yes
