Repository kubernetes-sigs/contributor-playground, pull requests merged in 2022-12, with the labels that each got.

#1025 Add s-kawamura-w664.md for ood-2022 demo
  japan/ood-2022/workdir/s-kawamura-w664.md
Labels: kind/documentation, lgtm, sig/node, size/XS, approved, cncf-cla: yes

#1027 Add ryo-ma.md
  japan/ood-2022/workdir/ryo-ma.md
Labels: kind/documentation, lgtm, sig/node, size/XS, approved, cncf-cla: yes

#1028 ADD KazuhitoSuda-NEC.md for odd-2022 demo
  japan/ood-2022/workdir/KazuhitoSuda-NEC.md
Labels: kind/documentation, lgtm, sig/node, size/XS, approved, cncf-cla: yes

#1026 Add shinichi-abe-dev.md for ood-2022.demo
  japan/ood-2022/workdir/shinichi-abe-dev.md
Labels: kind/documentation, lgtm, sig/node, size/XS, approved, cncf-cla: yes

#1030 add levi106.md for ood-2022
  japan/ood-2022/workdir/levi106.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1029 Add katsuharu.md for ood-2022 hands on
  japan/ood-2022/workdir/katsuharu.md
Labels: kind/documentation, lgtm, sig/node, size/XS, approved, cncf-cla: yes

#1033 Add tig.md
  japan/ood-2022/workdir/tig.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1034 Add i-kenta.md for ood-2022 demo
  japan/ood-2022/workdir/i-kenta.md
Labels: kind/documentation, lgtm, sig/node, size/XS, approved, cncf-cla: yes

#1031 Add takei-ryuichi.md
  japan/ood-2022/workdir/takei-ryuichi.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1037 add abe-039.md for ood-2022 demo
  japan/ood-2022/workdir/abe-039.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1042 Add ryo-honda.md
  japan/ood-2022/workdir/ryo-honda.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1032 commit doc file
  japan/ood-2022/workdir/sathish-macro.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1051 Fix typo of README.md
  japan/README.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1045 add ozaw
  japan/ood-2022/workdir/n-ozawa-w664
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1048 Add tomari-tatsuya.md
  japan/ood-2022/workdir/tomari-tatsuya.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1052 Add ito123456.md
  japan/ood-2022/workdir/ito123456.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1054 Add the photo on ood-2022
  japan/README.md
  japan/ood-2022/README.md
  japan/ood-2022/images/ood-2022-01.jpg
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1019 Update owners
  OWNERS
  remote/OWNERS
Labels: size/S, lgtm, approved, cncf-cla: yes

#1015 add frankyang-code4fun as remote learner
  remote/LEARNERS
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1016 add ggjulio to remote/LEARNERS
  remote/LEARNERS
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1055 Add `learners/` directory, to avoid conflict
  remote/README.md
  remote/learners/shu-mutou.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1056 Fix NOTE section
  remote/README.md
  remote/learners/LEARNERS
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes
