Repository kubernetes-sigs/contributor-playground, pull requests merged in 2024-10, with the labels that each got.

#1456 Add nasa9084 to remote OWNERS
  remote/OWNERS
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1457 Create `remote/learners/nicobistolfi.md
  remote/learners/nicobistolfi.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1435 add devemilio96.md to remote/learners folder
  remote/learners/devemilio96.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1393 Add sonu1311.md to remote/learners folder
  remote/learners/sonu1311.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1338 hello k8s
  remote/learners/hsunwenfang.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1455 Add remote/learners/coderocker.md for CLA signing purposes
  remote/learners/coderocker.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1452 Add remote/learners/ebblake.md for CLA signing purposes
  remote/learners/ebblake.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1463 add shakthi.md to remote learners
  remote/learners/shakthi.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1466 First commit
  remote/learners/joumanae.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1462 add yannkistenmacker.md to brazil folder
  brazil/YannKistenmacker.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1480 Make antonio a Kubernetes contributor 🙋‍♂️
  remote/learners/antonio.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1477 Make packetsnscripts a Kubernetes contributor
  remote/learners/siddharth.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1474 gangahiremath starts contribution in kubernetes community
  remote/learners/ganga.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1464 Add remote/learners/fan.md
  remote/learners/fan.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1461 create cosmeowpawlitan.md
  remote/learners/cosmeowpawlitan.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1467 add sumanjeet.md to remote/learners folder
  remote/learners/sumanjeet.md
Labels: size/S, lgtm, approved, cncf-cla: yes

#1468 Add `hoony9x.md` to `remote/learners`
  remote/learners/hoony9x.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1443 My first contibution to K8s playground
  remote/learners/Najeeb.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1433 add sudiproy.md to remote/learners folder
  remote/learners/sudiproy.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1428 Create john7doe
  remote/learners/john7doe
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1440 x-color starts contribution in the Kubernetes community
  remote/learners/x-color.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1431 Add rainystar.md to remote/learners folder
  remote/learners/rainystar.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1436 add gsstuart.md to remote/learners folder`.
  remote/learners/gsstuart.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1459 added praduman.md
  remote/learners/Praduman.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1460 Create karthik.md
  remote/learners/karthik.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1481 Add meowlvaro.md for practicing PR submissions
  remote/learners/meowlvaro.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1471 Add webgamedevelop.md
  remote/learners/webgamedevelop.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1482 add henrykhosasih.md to learners
  remote/learners/henrykhosasih.md
Labels: size/S, lgtm, approved, cncf-cla: yes

#1487 Add emc2016.md to remote/learners folder
  remote/learners/emc2016.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1490 add achrefothmani.md to learners
  remote/learners/achrefothmani.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1492 add Ali90922.md to remote/learners folder
  remote/learners/Ali90922.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1478 Added myself as a learner to sign CLA
  remote/learners/troll-os.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1494 Remove odl description about EasyCLA in japan folder
  japan/assets/attendee-prerequisites.md
Labels: lgtm, kind/cleanup, size/XS, approved, cncf-cla: yes

#1493 Add ssuji15
  remote/learners/ssuji15.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1495 Add vishuvenu to remote. First PR
  remote/learners/vishuvenu.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1500 Add chamarsh.md to remote/learners
  remote/learners/chamarsh.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1498 add kit_hung.md
  remote/learners/kit_hung.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1501 Add tarunsunny3.md file
  remote/learners/tarunsunny3.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1470 feat: add davidnuneslima.md
  remote/learners/davidnuneslima.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1502 [ja] Initialize 2024-11 k8s upstream training in Japan
  japan/cndw-2024/README.md
  japan/cndw-2024/images/.gitkeep
  japan/cndw-2024/workdir/.gitkeep
Labels: kind/feature, size/M, lgtm, approved, cncf-cla: yes

#1472 add austria folder + md file
  austria/awgrass.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1432 Add moreirayokoyama.md
  brazil/moreirayokoyama.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1347 CLA signature
  morocco/pr.txt
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1504 Add remote/learners/root30.md
  remote/learners/root30.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1503 Add remote/learners/brianmoran.md
  remote/learners/brianmoran.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1506 feat: add remote/learners/alemrtv.md to sign CLA
  remote/learners/alemrtv.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1508 add jddarby.md to remote/learners directory
  remote/learners/jddarby.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1510 Add movabs.md to remote/learners folder
  remote/learners/movabs.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1509 add kkoch986.md to remote/learners folder
  remote/learners/kkoch986.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1394 add hetjagani.md to remote/learners folder
  remote/learners/hetjagani.md
Labels: kind/feature, kind/design, kind/documentation, lgtm, kind/failing-test, kind/api-change, size/XS, approved, cncf-cla: yes
