Repository kubernetes-sigs/contributor-playground, pull requests merged in 2024-07, with the labels that each got.

#1256 Applying for CLA
  remote/learners/jamesd.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1266 Try signing CLA
  remote/learners/dmitris.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1268 Try signing CLA
  remote/learners/fyu17.md
Labels: lgtm, kind/flake, size/XS, approved, cncf-cla: yes

#1269 aborrero: CLA signing
  remote/learners/aborrero.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1272 signing cla for csauoss
  remote/learners/csauoss.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1273 Try to sign CLA
  remote/learners/flmichel.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1274 Sample to PR to sign the CLA
  remote/learners/pfuentesg.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1280 Create jeffinkottaram
  remote/learners/jeffinkottaram
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1285 PR to sign CLA
  remote/learners/Maalvi14.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1283 PR to sign CLA
  remote/learners/k8y.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1262 Create abhinovp just to sign the CLA
  india/remote/learners/abhinovp
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1287 Signing the SLA
  remote/learners/pranavt84.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1292 PR to sign CLA
  remote/learners/r0han22.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1294 Sign CLA
  remote/learners/ahmadkaleem2.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1295 Sign CLA
  remote/learners/lohit.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1297 Initial commit for signing CLA.
  remote/learners/radvanszki.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1300 Adding file to `remote/learners` to sign CLA
  remote/learners/l0rd
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1301 Create arseniizakharov.md to sign the CLA
  remote/learners/arseniizakharov.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1303 first contribution
  remote/learners/ajcaldelas.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1313 [ja] sandbox for Japanese upstream training
  japan/adhoc/workdir/Okabe-Junya.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1314 Update Japanese OWNERS for upstream training
  japan/OWNERS
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1311 Create jlhello.md to sign CLA
  remote/learners/jlhello.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1312 Create qianzhangxa
  remote/learners/qianzhangxa
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1325 Move mrbobbytables to emeritus
  OWNERS
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1326 [ja] Initialize 2024-08 k8s upstream training in Japan
  japan/cncj-202408/README.md
  japan/cncj-202408/images/.gitkeep
  japan/cncj-202408/workdir/.gitkeep
Labels: kind/feature, size/S, lgtm, approved, cncf-cla: yes
