Repository kubernetes-sigs/contributor-playground, pull requests merged in 2024-09, with the labels that each got.

#1395 add cris-x.md to remote/learners folder
  remote/learners/cris-x.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1398 add souheilbenslama as a learner
  remote/learners/souheilbenslama.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1401 Add kawahata.md into cncj-202408
  japan/cncj-202408/workdir/kawahata.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1399 Create lai3d.md
  remote/learners/lai3d.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1407 added walt.md to remote/learners folder
  remote/learners/walt.md
Labels: kind/bug, lgtm, size/XS, approved, cncf-cla: yes

#1411 add alessandrofazio.md to remote/learners folder
  remote/learners/alessandrofazio.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1412 add kripu.md to remote/learners folder
  remote/learners/kripu.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1409 Create sarevalo2002.md
  remote/learners/sarevalo2002.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1410 add petahhh.md to remote/leaners
  remote/learners/petahhh.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1406 Sign CLA
  remote/learners/unvavo.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1405 add CefBoud.md toremote/learners dir
  remote/learners/CefBoud
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1402 add ish.md to sign the CLA
  remote/learners/ish.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1403 Add kingbj940429 as a learner
  remote/learners/kingbj940429.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1408 add remote/learners/zedawg.md for sign cla
  remote/learners/zedawg.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1414 Add osatest.md into adhoc
  japan/adhoc/workdir/osatest.md
Labels: lgtm, sig/testing, sig/docs, size/XS, approved, cncf-cla: yes

#1415 Create youwalther65.md
  remote/learners/youwalther65.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1417 Create yuyabee to sign the CLA
  remote/learners/yuyabee.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1418 add russellcain.md to remote/learners folder
  remote/learners/russellcain.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1404 chore: add anurag252.md to remote/learners folder
  remote/learners/anurag252.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1454 Create kplachkov.md
  remote/learners/kplachkov.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1449 add /remote/learners/ghazimuharam.md for CLA sign
  remote/learners/ghazimuharam.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1442 add yongruilin to remote learner dir
  remote/learners/yongruilin.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1444 Add raghuramlavan to remote. First PR
  remote/learners/raghu.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1441 Create reematcs
  remote/learners/reematcs
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1445 Adds rogvc as a contributor
  remote/learners/rogvc.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1446 add mateo.md to remote/learners folder
  remote/learners/mateo.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1447 Create arjundandagi.md
  remote/learners/arjundandagi.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1450 add ebouvard to sign CLA
  remote/learners/ebouvard.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1451 Add alexanderstephan.md to sign CLA
  remote/learners/alexanderstephan.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes
