Repository kubernetes-sigs/contributor-playground, pull requests merged in 2024-03, with the labels that each got.

#1162 Added learners/nielsreijers.md
  remote/learners/nielsreijers.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1164 Create amirabbas8.md
  remote/learners/amirabbas8.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1167 Test PR for CLA Signing
  remote/learners/agoel25.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1171 Add affiliations
  japan/cncj-202403/README.md
Labels: size/S, lgtm, approved, cncf-cla: yes

#1168 Add introduction for Anvesh to contribute to Kubernetes community
  remote/learners/anveshjhuboo.md
Labels: size/S, lgtm, approved, cncf-cla: yes

#1169 added my readme
  remote/learners/jesslane94.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1174 Add ziyi.md into cncj-202403 for demo
  japan/cncj-202403/workdir/ziyi.md
Labels: lgtm, sig/testing, sig/node, size/XS, approved, cncf-cla: yes

#1177 Add japan4415.md into cncj-202403 for demo
  japan/cncj-202403/workdir/japan4415.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1181 add Akiyama.md into cncj-202403 for demo
  japan/cncj-202403/workdir/akiyama.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1178 add japan/cncj-202403/workdir/date for demo
  japan/cncj-202403/workdir/date
Labels: lgtm, sig/testing, sig/node, size/XS, approved, cncf-cla: yes

#1179 add rei.md
  japan/cncj-202403/workdir/rei.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1180 Add wattmto.md
  japan/cncj-202403/workdir/wattmto.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1182 Add bumpei.md into cncj-202403 for demo
  japan/cncj-202403/workdir/bumpei.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1183 Add robertcal.md into cncj-202403
  japan/cncj-202403/workdir/robertcal.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1184 Add yuki.md
  japan/cncj-202403/workdir/yuki.md
Labels: kind/design, lgtm, size/XS, approved, cncf-cla: yes

#1185 Add kohshi.md into cncj-202403 for practice
  japan/cncj-202403/workdir/kohshi.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1186 add ymaki.md to cncj-202403 for training
  japan/cncj-202403/workdir/ymaki.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1187 Add hoshymo.md into cncj-202403 for demo
  japan/cncj-202403/workdir/hoshymo.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1188 add foo_kzks.md into cncj-202403
  japan/cncj-202403/workdir/foo_kzks.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1189 Add kaitok.md
  japan/cncj-202403/workdir/kaitok.md
Labels: lgtm, sig/testing, sig/node, size/XS, approved, cncf-cla: yes

#1192 Add murasame29 md
  japan/cncj-202403/workdir/foo.md
  japan/cncj-202403/workdir/murasame29.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1193 Add ymatsuda04.md
  japan/cncj-202403/workdir/ymatsuda04.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1194 Add guideline.md into cncj-202403 for demo
  japan/cncj-202403/workdir/guideline.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1195 Add koba.md
  japan/cncj-202403/workdir/koba.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1196 Add test.md
  japan/cncj-202403/workdir/test.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1198 Add kazuya.md into cncj-202403 for demo
  japan/cncj-202403/kazuya.md
Labels: kind/documentation, lgtm, sig/testing, sig/node, size/XS, approved, cncf-cla: yes

#1200 Add mmakmo.md
  japan/cncj-202403/workdir/mmakmo.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1203 Add dkmats.md to cncj202403 for demo
  japan/cncj-202403/workdir/dkmats.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1205 Add group photos for CNCJ-202403
  japan/README.md
  japan/cncj-202403/README.md
  japan/cncj-202403/images/cncj-202403-01.png
  japan/cncj-202403/images/cncj-202403-02.png
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1206 Remove the section for next schedule in Japan
  japan/README.md
Labels: lgtm, kind/cleanup, size/XS, approved, cncf-cla: yes

#1207 Add shinji.md
  japan/cncj-202403/workdir/shinji.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1208 first commit
  brazil/fstsantos.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1211 test yt
  remote/learners/test-yt.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1210 first commit
  remote/learners/tronskywalker.md
Labels: size/S, lgtm, approved, cncf-cla: yes, ¯\_(ツ)_/¯
