Repository kubernetes-sigs/contributor-playground, pull requests merged in 2024-08, with the labels that each got.

#1331 Try to sign the CLA
  remote/learners/sasanbabai.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1316 Sudomarko sign CLA
  remote/learners/Sudomarko.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1318 letajmal sign CLA
  remote/learners/letajmal.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1319 sign cla
  remote/learners/qincwang.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1332 cla sign
  remote/learners/sirsam21.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1333 Sign CLA
  remote/learners/exobitt.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1336 Create rezkam.md to sign the CLA
  remote/learners/rezkam.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1334 Add travisyx.md to remote/learners
  remote/learners/travisyx.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1335 Github user Shumakriss ready to sign CLA
  remote/learners/shumakriss.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1350 Fix typo in README in `japan`
  japan/README.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1299 Clarify the submit target for PR
  README.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1374 Add ziyi.md into cncj-202408
  japan/cncj-202408/workdir/ziyi.md
Labels: lgtm, sig/testing, sig/docs, size/XS, approved, cncf-cla: yes

#1375 Add NT-marlowe.md into cncj-202408
  japan/cncj-202408/workdir/NT-marlowe.md
Labels: kind/documentation, lgtm, sig/testing, sig/docs, size/XS, approved, cncf-cla: yes

#1377 Added jagrament.md into cncj-202408
  japan/cncj-202408/workdir/jagrament.md
Labels: kind/documentation, lgtm, sig/testing, sig/docs, size/XS, approved, cncf-cla: yes

#1379 Add yukinakanaka.md into cncj-202408
  japan/cncj-202408/workdir/yukinakanaka.md
Labels: lgtm, sig/testing, size/XS, approved, cncf-cla: yes

#1376 feat: add honahuku.md
  japan/cncj-202408/workdir/honahuku.md
Labels: kind/documentation, lgtm, sig/testing, sig/docs, size/XS, approved, cncf-cla: yes

#1378 Add donkooo.md
  japan/cncj-202408/workdir/donkooo.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1382 update link to code-of-conduct in japan attendee prerequisites
  japan/assets/attendee-prerequisites.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1381 Add koukoji18.md into cncj-202408
  japan/cncj-202408/workdir/koukoji18.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1383 doc: add missed word in japan/attendee-prerequisites.md
  japan/assets/attendee-prerequisites.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1388 Upload image for upstream training in Japan
  japan/README.md
  japan/cncj-202408/README.md
  japan/cncj-202408/images/cncj-kutj-2024-08.png
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1373 Create kvifern.md to sign the CLA
  remote/learners/kvifern.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1372 Signing CLA
  remote/learners/chamodshehanka.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1370 Try to sign the CLA
  remote/learners/melanmeg.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1366 Create rgau823
  remote/learners/rgau823.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1364 Signing the K8s CLA
  remote/learners/sadasu.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1360 Create wallee94 to sign the CLA
  remote/learners/wallee94.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1355 Sign the CLA
  remote/learners/jansch
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1349 Cla sign
  remote/learners/Daulat1249.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1343 Create ruoyu.md
  remote/learners/ruoyu.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1340 Added andreidon.md to remote/learners folder
  remote/learners/andreidon.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1339 Add sshambar.md to remote/learners folder
  remote/learners/sshambar.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1341 sign cla
  remote/learners/airwings.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1342 Create karthikmurakonda.md
  remote/learners/karthikmurakonda.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1344 Create martinkunc just to sign the CLA
  remote/learners/martinkunc
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1345 Sign CLA
  remote/learners/veber.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1353 Sign the CLA
  remote/learners/d2m2.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1356 CCLA
  remote/learners/balaramesh2.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1361 Sign the CLA
  remote/learners/anneheartrecord.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1363 Try to sign the CLA
  remote/learners/kang.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1367 Add new contributor mashasht.
  remote/learners/mashasht.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1368 Create ElioDiNino.md
  remote/learners/ElioDiNino.md
Labels: kind/feature, lgtm, size/XS, approved, cncf-cla: yes

#1369 sign cla by saiaunghlyanhtet
  remote/learners/saiaunghlyanhtet.md
Labels: kind/feature, size/S, lgtm, approved, cncf-cla: yes

#1384 create hcc429 to sign the CLA
  remote/learners/hcc429.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1387 Create RamBITS-AI just to sign the CLA
  remote/learners/RamBITS-AI
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1389 add ziyi.md to remote/learners folder
  remote/learners/ziyi.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1390 Add kotaki.md
  japan/cncj-202408/workdir/kotaki.md
Labels: lgtm, size/XS, approved, cncf-cla: yes
