Repository kubernetes-sigs/contributor-playground, pull requests merged in 2025-08, with the labels that each got.

#1923 Add brazil/WagnerFerreira.md for registation.
  brazil/WagnerFerreira.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#2063 add wesleynepo
  brazil/wesleynepo.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#2068 sign the CLA and add rodrigues-daniel.md to remote/learners
  remote/learners/rodrigues-daniel.md
Labels: kind/documentation, size/M, lgtm, approved, cncf-cla: yes

#2062 add chetanxrathore.md to remote/learners folder
  remote/learners/chetanxrathore.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#2058 Add khurshid.md to remote/learners
  india/remote/learners/khurshid.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#2045 Ic-venkat.md adding into the contribution.
  remote/learners/Ic-venkat.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1777 add silbermannnn.md to remote/learners folder
  remote/learners/silbermannnn.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1911 Practice PR - Add ffrod.md to the remote/learners folder
  remote/learners/ffrod.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#2048 Add shemsu to learners
  remote/learners/Adilshemsu.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#2069 add justlorain to remote/learners
  remote/learners/justlorain.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#2070 Add zeqian-meng.md to remote/learners
  remote/learners/zeqian-meng.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#2074 Add dchaloupka learner
  remote/learners/dchaloupka.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#2077 Add ketanjani21.md
  remote/learners/ketanjani21.md
Labels: size/S, kind/documentation, lgtm, approved, cncf-cla: yes

#2093 Add greeting for Dongbin in dongbin.md
  remote/learners/dongbin.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes, ¯\_(ツ)_/¯

#2083 chuyang-deng signing CLA.
  remote/learners/chuyang-deng.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#2095 create linMax-dev.md
  remote/learners/linMax-dev.md
  remote/learners/shehab.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#2091 Create nikos445.md to remote/learners folder
  remote/learners/nikos445.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#2079 add seidigapbar.md to remote/learners folder
  remote/learners/seidigapbar.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#2088 Add TobyTheHutt.md to remote/learners
  remote/learners/TobyTheHutt.md
Labels: size/S, kind/documentation, lgtm, approved, cncf-cla: yes

#2092 feat: add rooobinye.md
  remote/learners/rooobinye.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#2096 Adding veepeeaee to remote/learners
  remote/learners/veepeeaee.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#2103 Update OWNERS
  brazil/OWNERS
Labels: lgtm, size/XS, approved, cncf-cla: yes
