Repository kubernetes-sigs/contributor-playground, pull requests merged in 2025-04, with the labels that each got.

#1796 add iropz.md to remote/learners folder
  remote/learners/iropz.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1780 Add Edax97 to remote/learners
  remote/learners/edax97.md
Labels: kind/documentation, size/M, lgtm, approved, cncf-cla: yes

#1781 my first contribution to k8s
  remote/learners/calebandria.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1782 Add leulmes.md to remote/learners folder
  remote/learners/leulmes.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1783 add mocz.md to remote/learners folder
  remote/learners/mocz.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1784 Create limbaniharsh.md for CLA
  remote/learners/limbaniharsh.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1776 add azych.md to remote/learners folder
  remote/learners/azych.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1772 creating teaglebuilt.md in remote learners
  remote/learners/teaglebuilt.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1766 adding my learner markdown file
  remote/learners/freexploit.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1765 add natitomattis.md to remote/learners folder
  remote/learners/natitomattis.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1769 add u-kai.md to remote/learners folder
  remote/learners/u-kai.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1785 add remote/learners/gdromanov.md
  remote/learners/gdromanov.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1786 add rltrancodex.md to remote/learners for CLA signing
  remote/learners/rltrancodex.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1787 Add ronaldngounou.md to remote/learners
  remote/learners/ronaldngounou.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1790 Initial PR from akhiljain23 for signing CLA
  remote/learners/akhil.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1791 feat: Add danielkimb.md
  remote/learners/danielkimb.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1793 add LuigiDotSRC.md to remote/learners folder
  remote/learners/LuigiDotSRC.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1795 add y-isono.md to remote/learners folder
  remote/learners/y-isono.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1797 add harshit77.md to remote/learners folder
  remote/learners/harshit77.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1799 add chaewon.md to remote/learners folder
  remote/learners/chaewon.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1800 Starting small !! more to go ワクワク
  remote/learners/nikeshmaharja.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1805 add ogu1208.md to remote/learners folder for CLA Signing
  remote/learners/Ogu1208.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1803 0th PR more to go........ !! Jai Shri Ram !!
  remote/learners/ramasurendra.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1804 Complete CLA signing for future contributions
  remote/learners/Rohit-wagh.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1802 add shu-mutou as root OWNERS
  OWNERS
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1775 PR for signing CLA - Hello from Czech
  czechia/OWNERS
  czechia/README.md
  czechia/prague/README.md
Labels: size/S, kind/documentation, lgtm, approved, cncf-cla: yes

#1774 Merge feature/hello-world to master #1773
  czechia/OWNERS
  czechia/prague/README.md
Labels: size/S, kind/documentation, cncf-cla: yes

#1635 add shyamin.md to remote/learners folder for CLA Signing
  remote/learners/shyamin.md
Labels: lgtm, size/XS, approved, lifecycle/stale, cncf-cla: yes

#1806 add tobi.md to remote/lerners folder
  remote/learners/tobi.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1807 add petern48.md to remote/learners folder
  remote/learners/petern48.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1808 add drlatt.md to remote/learners folder
  remote/learners/drlatt.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1677 commit for CLA
  india/remote/learners/navinkumar.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1817 add georgehyde-dot.md to remote/learners folder
  remote/learners/georgehyde-dot.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1814 Add itspacchu.md for CLA signing
  india/remote/learners/itspacchu.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1810 add bryagd.md to remote/learners folder for CLA Signing
  remote/learners/bryagd.md
Labels: size/S, lgtm, approved, cncf-cla: yes

#1811 add nhochamvui.md to remote/learners folder
  remote/learners/nhochamvui.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1812 CLA assignment
  remote/learners/jonataswingeter.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1815 add arunjunai.md to remote/learners folder
  remote/learners/arunjunai.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1816 Add vg.md to remote/learners folder
  remote/learners/vg.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1820 Add sultetveny.md to "remote/learners" folder
  remote/learners/sultetveny.md
Labels: kind/documentation, size/M, lgtm, approved, cncf-cla: yes, ¯\_(ツ)_/¯
