Repository kubernetes-sigs/contributor-playground, pull requests merged in 2025-05, with the labels that each got.

#1831 add misterderpie.md to remote/learners folder
  remote/learners/misterderpie.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1825 Add bupd.md to remote/learners
  remote/learners/bupd.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1821 Adds new learner to remote/learners
  remote/learners/suyash-811.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1822 add umbertocicciaa.md to remote/learners folde
  remote/learners/umbertocicciaa.md
Labels: size/S, lgtm, approved, cncf-cla: yes

#1826 add liuzeyu.md to remote/learners folder
  remote/learners/liuzeyu.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1829 Add dylanzenner.md into /remote/learners/ folder
  remote/learners/dylanzenner.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1830 add tomwang57.md to remote/learners folder
  remote/learners/tomwang57.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1833 Update davidbaena.md remote entry
  remote/learners/davidbaena.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1834 Create swapnil-feature
  remote/learners/swapnil-feature
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1835 Add cbbond to remote/learners
  remote/learners/cbbond.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1837 Added rsingh0101 to remote/learners
  remote/learners/rsingh0101.txt
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1864 Update README for CNDS2025
  japan/cnds-2025/README.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1868 add sera.md into cnds-2025
  japan/cnds-2025/workdir/sera.md
Labels: kind/documentation, lgtm, sig/testing, sig/docs, size/XS, approved, cncf-cla: yes

#1867 add ziyi.md into cnds-2025
  japan/cnds-2025/workdir/ziyi.md
Labels: lgtm, sig/testing, sig/docs, size/XS, approved, cncf-cla: yes

#1869 add tmurakam.md to japan/cnds-2025/workdir
  japan/cnds-2025/workdir/tmurakam.md
Labels: kind/documentation, lgtm, sig/testing, sig/docs, size/XS, approved, cncf-cla: yes

#1866 Add foo.md
  japan/cnds-2025/workdir/foo.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1871 Add yusuke-sugiyama.md into cnds-2025
  japan/cnds-2025/workdir/yusuke-sugiyama.md
Labels: kind/documentation, lgtm, sig/testing, sig/docs, size/XS, approved, cncf-cla: yes

#1872 Add wa6sn.md into CNDS2025
  japan/cnds-2025/workdir/wa6sn.md
Labels: kind/documentation, lgtm, sig/testing, sig/docs, size/XS, approved, cncf-cla: yes

#1873 Add kitsuyaazuma.md
  japan/cnds-2025/workdir/kitsuyaazuma.md
Labels: kind/documentation, lgtm, sig/testing, sig/docs, size/XS, approved, cncf-cla: yes

#1875 Add sh05.md into cnds-2025
  japan/cnds-2025/workdir/sh05.md
Labels: kind/documentation, lgtm, sig/testing, sig/docs, size/XS, approved, cncf-cla: yes

#1877 Add sanghyuklee.md into japan/cnds-2025
  japan/cnds-2025/workdir/sanghyuklee.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1878 add r-hnf.md into cnds-2025
  japan/cnds-2025/workdir/r-hnf.md
Labels: kind/documentation, lgtm, sig/testing, sig/docs, size/XS, approved, cncf-cla: yes

#1879 Add kurita.md into japan/cnds-2025/workdir
  japan/cnds-2025/workdir/kurita.md
Labels: kind/documentation, lgtm, sig/testing, sig/docs, size/XS, approved, cncf-cla: yes, ¯\_(ツ)_/¯

#1882 Add kurosu.md
  japan/cnds-2025/workdir/kurosu.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1883 Add hiroshi.md
  japan/cnds-2025/workdir/hiroshi.md
Labels: lgtm, sig/testing, sig/docs, size/XS, approved, cncf-cla: yes

#1885 add saito.md
  japan/cnds-2025/workdir/saito.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1886 CNDS2025 report
  japan/README.md
  japan/cnds-2025/README.md
  japan/cnds-2025/images/CNDS2025-hybrid.jpg
  japan/cnds-2025/images/CNDS2025-remote.png
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes
