Repository kubernetes-sigs/contributor-playground, pull requests merged in 2025-01, with the labels that each got.

#1469 Create deepsh4h.md
  remote/learners/deepsh4h.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1632 Added noahwicz.md to the remote/learners directory for practicing PR submission
  remote/learners/noahwicz.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1629 add anant_raj.md to remote/learners folder
  remote/learners/anant_raj.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1626 Add first PR for CLA signing
  remote/learners/shubhamch71.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1625 adding a new contributor
  remote/learners/linde.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1627 Add my first PR for CLA signing
  remote/learners/Sakshich001.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1630 First PR + Signing CLA
  remote/learners/omkar_nag.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1631 Added simonfogliato.md in remote/learners.
  remote/learners/simonfogliato.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1633 add rbaturov.md to remote/learners folder
  remote/learners/rbaturov.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1634 add himanshujaindev
  remote/learners/himanshujaindev.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1639 first commit
  brazil/ViniciusPires.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1636 Create Mephistopheles2.md
  remote/learners/Mephistopheles2.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1637 First PR and Signing CLA
  remote/learners/jiahuipaung.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1638 Create sohamsengupta17.md
  remote/learners/sohamsengupta17.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1641 [added] my 1st contrib to test PR
  remote/learners/talnetd.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1642 add yverma.md to remote/learners folder
  remote/learners/yverma.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1644 Sign CLA
  remote/learners/lcpulzone.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1645 add saf1u to learners
  remote/learners/saf1u.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1648 add seagyn.ms to remote/learners folder
  remote/learners/seagyn.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1658 Create miseratio.md / signing CLA
  remote/learners/miseratio.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1671 Add z63d.md
  japan/cncj-202403/workdir/z63d.md
Labels: lgtm, sig/node, size/XS, approved, cncf-cla: yes

#1670 Signing the CLA and practicing PR
  remote/learners/sai-adarsh.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1660 Add remote/learners/attyxy.md
  remote/learners/attyxy.md
Labels: size/S, kind/documentation, lgtm, approved, cncf-cla: yes

#1657 Add GarrickHe.md to remote/learners
  remote/learners/GarrickHe.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1653 add remote/learners/mochivi.md
  remote/learners/mochivi.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1662 Create Matthiasbrat.md
  remote/learners/Matthiasbrat.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1673 Add yanai_2nd md
  remote/learners/yanai.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1665 Signing the CLA and practicing PR
  remote/learners/amy.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1659 signing CLA
  remote/learners/paulofponciano.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1674 Joining-k8s-opensource
  remote/learners/wieczorekpatryk.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1429 add mpelekh.md to remote/learners folder
  remote/learners/mpelekh.md
Labels: lgtm, size/XS, approved, lifecycle/stale, cncf-cla: yes

#1438 add eliesercla to remote/learners folder
  remote/learners/eliesercla
Labels: kind/documentation, lgtm, size/XS, approved, lifecycle/stale, cncf-cla: yes

#1672 add arel.md to remote/learners folder.
  remote/learners/arel.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1681 yurizf CLA signing
  remote/learners/yurizf.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1680 Create russd2357.md
  remote/learners/russd2357.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1682 docs: add mridha.md to remote/learners folder
  remote/learners/mridha.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes
