Repository kubernetes-sigs/contributor-playground, pull requests merged in 2025-07, with the labels that each got.

#1993 add pagwin.md to remote/learners folder
  remote/learners/pagwin.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1990 checking cla
  remote/learners/edwardviaene.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1992 Add virsuryaircas to learners directory
  india/remote/learners/virsuryaircas.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1986 adding vishwa357.md to remote/learners
  remote/learners/vishwa357.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1971 add onasser.md to remote/learners
  remote/learners/onasser.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1982 Add ah-tonmoy.md into remote/learners folder
  remote/learners/ah-tonmoy.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1980 Create LucasE.md
  remote/learners/LucasE.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1979 Add timothy-spencer.md page to /remote/learners
  remote/learners/timothy-spencer.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1976 Add aledesatg.md to remote/learners
  remote/learners/aledesatg.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1972 add sandeep.md to india/remote/learners folder
  india/remote/learners/sandeep.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1966 SoLongAndThanksForAllTheFish.md into remote/learners folder
  remote/learners/solongandthanksforallthefish.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1977 Add tylenwells.md into remote/learners folder
  remote/learners/tylenwells.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1984 add canyonjs.md to remote/learners dir
  remote/learners/canyonjs.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1987 add eanveden.md to remote/learners folder
  remote/learners/eanveden.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1988 add pramod.md to remote/learners folder
  remote/learners/pramod.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1994 Add mudit.md to remote/learners
  remote/learners/mudit.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#2004 Making change to sign the CLA
  brazil/luarch.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#2010 add coldinke.md to remote/learners folder
  remote/learners/coldinke.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#2006 add siddharth.md to /india/remote/learners folder
  india/remote/learners/siddharth.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#2001 Create add-Rez.md
  remote/learners/add-Rez.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1998 Add zohaib.md to remote/learners folder
  remote/learners/zohaib.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#2002 Add samuelmckean.md
  remote/learners/samuelmckean.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#2003 Add daniel.md to remote/learners directory
  remote/learners/daniel.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#2008 feat(brianrobt.md): add new learner introduction for brianrobt
  remote/learners/brianrobt.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#2009 add antoine.md to remote/learners folder for CLA Signing
  remote/learners/antoine.md
Labels: size/S, lgtm, approved, cncf-cla: yes

#2012 Create wannfq.md
  remote/learners/wannfq.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#2031 Add kamothi.md to remote/learners
  remote/learners/kamothi.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#2016 Add hankfreund.md to remote/learners folder.
  remote/learners/hankfreund.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#2017 Add arunkp.md to remote/learners folder
  remote/learners/arunkp.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#2023 Add sats.md to india/remote/learners
  india/remote/learners/sats.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#2030 add S0okJu.md to remote/learners folder
  remote/learners/S0okJu.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#2033 Create wonyongg.md to remote/learners
  remote/learners/wonyongg.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#2035 add rutigs.md to remote/learners
  remote/learners/rutigs.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#2044 Create thiago-pereira.md
  brazil/thiago-pereira.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#2054 Create aoi1.md
  remote/learners/aoi1.md
Labels: kind/documentation, lgtm, sig/testing, sig/docs, size/XS, approved, cncf-cla: yes

#2052 add yomek33.md into remote/learners
  remote/learners/yomek33.md
Labels: kind/documentation, lgtm, sig/testing, sig/docs, size/XS, approved, cncf-cla: yes

#2055 Add mihohoi.md
  remote/learners/mihohoi.md
Labels: kind/documentation, lgtm, sig/testing, sig/docs, size/XS, approved, cncf-cla: yes
