Repository kubernetes-sigs/contributor-playground, pull requests merged in 2025-06, with the labels that each got.

#1907 Add d0w.md to remote/learners folder
  remote/learners/d0w.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1895 added jlyon.md to remote/learners folder
  remote/learners/jlyon.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1896 add condaatje
  remote/learners/condaatje.org
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1897 Add gk16.md to remote/learners folder
  remote/learners/gk16.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1894 feat: add yaruyng's learn.md
  remote/learners/yaruyng.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1853 add file for CLA
  remote/learners/yujen77300.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1849 Create aletundo.md to sign CLA and start contributing
  remote/learners/aletundo.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1840 add MattIvan.md to remote/learners folder
  remote/learners/MattIvan.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1789 Add my username to contributor playground
  india/remote/learners/pawaspy.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1798 Create dhild.md
  remote/learners/dhild.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1850 added jmathews1.md file
  remote/learners/jmathews1.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1851 Add/han md
  remote/learners/han.md
  remote/learners/limhan.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1860 Create Chaitra.md
  india/remote/learners/Chaitra.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1887 Create sonnysideup3796.md
  remote/learners/sonnysideup3796.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1889 create nagarajRPoojari.md
  remote/learners/nagarajRPoojari.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1891 add hotkeyprince.md to remote/learners folder
  remote/learners/hotkeyprince.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1898 add superalloy.md to support signing the CLA
  remote/learners/superalloy.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1903 Create 88abb.md
  remote/learners/88abb.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1906 Create badhezi.md
  remote/learners/badhezi.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1910 Add kevlar.md to remote/learners
  remote/learners/kevlar.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1827 PR for entlein to sign the CLA
  austria/clasign.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1941 Add sreeram-venkitesh (for tmp use)
  japan/OWNERS
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1943 Add ziyi.md into japan/japan-community-day-2025
  japan/japan-community-day-2025/workdir/ziyi.md
Labels: lgtm, sig/testing, sig/docs, size/XS, approved, cncf-cla: yes

#1942 Add kei01234kei.md
  japan/japan-community-day-2025/workdir/kei01234kei.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1944 Add kkato.md into japan/japan-community-day-2025
  japan/japan-community-day-2025/workdir/kkato.md
Labels: kind/documentation, lgtm, sig/testing, sig/docs, size/XS, approved, cncf-cla: yes

#1945 Add hayashino.md into japan/japan-community-day-2025/workdir
  japan/japan-community-day-2025/workdir/hayashino.md
Labels: kind/documentation, lgtm, sig/testing, sig/docs, size/XS, approved, cncf-cla: yes

#1946 Add distkloc.md into japan/japan-community-day-2025
  japan/japan-community-day-2025/workdir/distkloc.md
Labels: kind/documentation, lgtm, sig/docs, size/XS, approved, cncf-cla: yes

#1947 Add gokkenroko.md into japan/japan-community-day-2025
  japan/japan-community-day-2025/workdir/gokkenroko.md
Labels: kind/documentation, lgtm, sig/testing, sig/docs, size/XS, approved, cncf-cla: yes

#1951 Add tai_dinh.md into japan/japan-community-day-2025
  japan/japan-community-day-2025/workdir/tai_dinh.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1952 Add kawakami.md in to japan/japan-community-day-2025/workdir
  japan/japan-community-day-2025/workdir/kawakami.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1953 Add 74th.md to japan/japan-community-day-2025
  japan/japan-community-day-2025/workdir/74th.md
Labels: kind/documentation, lgtm, sig/testing, sig/docs, size/XS, approved, cncf-cla: yes

#1954 Add murai.md to japan/japan-community-day-2025
  japan/japan-community-day-2025/workdir/murai.md
Labels: kind/documentation, lgtm, sig/docs, size/XS, approved, cncf-cla: yes

#1918 Added account to learners
  remote/learners/Aarya2004.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1957 Add Subaru365.md
  japan/adhoc/workdir/Subaru365.md
Labels: kind/documentation, lgtm, sig/docs, size/XS, approved, cncf-cla: yes

#1968 Add bourgeoisor.md to remote/learners
  remote/learners/bourgeoisor.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1962 Add gemmahou.md to remote/learners
  remote/learners/gemmahou.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1932 Create Behiuu.md
  remote/learners/Behiuu.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1914 Add learners/inkel.md
  remote/learners/inkel.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1916 Create sahay-shashank.md
  india/remote/learners/sahay-shashank.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1925 added gokul.md to remote learners
  india/remote/learners/gokul.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1926 add lisadd.md to remote/learners folder
  remote/learners/lisadd.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1938 add nsunkad.md to remote/learners
  remote/learners/nsunkad.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1939 Adding aleonidex.md into remote/learners for CLA purpose
  remote/learners/aleonidex.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1959 Signing the CLA
  remote/learners/maqiuyu
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1960 Add lzhai.md to remote/leaners
  remote/learners/lzhai.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1961 add rostik_bobo.md to remote/learners folder
  remote/learners/rostik_bobo.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1963 my first commit & first PR in K8s
  india/remote/learners/bharath.md
Labels: lgtm, size/XS, approved, cncf-cla: yes

#1964 Add kaston.md to remote/learners folder
  remote/learners/kaston.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes

#1967 add taran.md to remote/learners to sign cla
  remote/learners/taran.md
Labels: kind/documentation, lgtm, size/XS, approved, cncf-cla: yes
